apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ga9i8ul3o-go 
  janus-idp.io/tekton: ga9i8ul3o-go
  backstage.io/kubernetes-id: ga9i8ul3o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ga9i8ul3o-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml