apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ga9i8ul3o-go-gitops
  description: This is GitOps manifest for ga9i8ul3o-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ga9i8ul3o-go
    backstage.io/kubernetes-id: ga9i8ul3o-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ga9i8ul3o-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ga9i8ul3o-go
