apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ga9i8ul3o-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ga9i8ul3o-go 
  name: ga9i8ul3o-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ga9i8ul3o-go 
