apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ga9i8ul3o-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:4f3f06d078d3a02683b2e532cdb9d4f8c699531a@sha256:97a36cbd9a364612430ab3b20c9e12125e0d2ad5010b7aaa84835540166c5fa5
          name: container-image
